// Prüft die Videonachricht: aufnehmen, abspielen, nach Neustart vorhanden, sichern, nicht in der Datei, löschen.
import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
import { spawn, execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';
const hier = path.dirname(new URL(import.meta.url).pathname);
const erg = path.join(hier, 'ergebnisse');
const video = path.join(erg, 'testvideo.webm');
execFileSync('ffmpeg', ['-y', '-loglevel', 'error', '-f', 'lavfi', '-i', 'testsrc=duration=3:size=320x240:rate=15', '-c:v', 'libvpx', '-b:v', '200k', video]);
const groesse = fs.statSync(video).size;
const server = spawn('python3', ['-m', 'http.server', '8127', '--bind', '127.0.0.1'], { cwd: path.join(hier, '../docs'), stdio: 'ignore' });
await new Promise(r => setTimeout(r, 800));
const pruef = (was, ja) => console.log(`  ${ja ? 'ok ' : 'FEHLT'} ${was}`);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const fehler = [];
try {
  const p = await (await browser.newContext({ locale: 'de-DE', acceptDownloads: true })).newPage();
  await p.addInitScript(() => { delete window.showOpenFilePicker; delete window.showSaveFilePicker; window.print = () => {}; });
  p.on('pageerror', e => fehler.push(e.message));
  p.on('console', m => { if (m.type() === 'error') fehler.push(m.text()); });
  await p.goto('http://localhost:8127/app/');
  await p.click('#btnNeu');
  await p.waitForSelector('.kacheln');
  await p.click('#navliste button[data-id=nachricht]');
  pruef('Karte Videonachricht vorhanden', await p.isVisible('h3:has-text("Videonachricht")'));
  const [wahl] = await Promise.all([p.waitForEvent('filechooser'), p.click('button:has-text("Video aufnehmen")')]);
  pruef('Aufnahme startet die Frontkamera', await p.getAttribute('#videowahl', 'capture') === 'user');
  await wahl.setFiles(video);
  await p.waitForSelector('video.videonachricht');
  const meta = await p.evaluate(() => new Promise(ok => { const v = document.querySelector('video.videonachricht'); if (v.readyState >= 1) ok(v.duration); v.onloadedmetadata = () => ok(v.duration); v.onerror = () => ok(-1); setTimeout(() => ok(-2), 5000); }));
  pruef('Video lässt sich abspielen (Dauer ' + meta.toFixed(1) + ' s)', meta > 2.5 && meta < 3.5);
  pruef('Hinweis noch nicht gesichert', (await p.textContent('.videobereich .hilfe')).includes('Noch nicht gesichert'));
  await p.reload();
  await p.click('.kachel:has-text("Persönliche Nachricht")').catch(() => p.click('#navliste button[data-id=nachricht]'));
  await p.waitForSelector('video.videonachricht', { timeout: 5000 }).catch(() => {});
  pruef('Video nach Neustart noch da', await p.locator('video.videonachricht').count() === 1);
  const [dl] = await Promise.all([p.waitForEvent('download'), p.click('button:has-text("Video sichern")')]);
  pruef('Video als Datei gesichert', dl.suggestedFilename() === 'Videonachricht.webm' && fs.statSync(await dl.path()).size === groesse);
  await p.waitForFunction(() => document.querySelector('.videobereich .hilfe')?.textContent.includes('Zuletzt gesichert'));
  pruef('Sicherungsdatum angezeigt', true);
  await p.fill('#inhalt input[type=text] >> nth=-1', 'USB-Stick im Ordner Testament');
  const [ordner] = await Promise.all([p.waitForEvent('download'), p.click('#btnMehr').then(() => p.click('#btnSpeichern'))]);
  await p.click('dialog[open] button:has-text("Verstanden")').catch(() => {});
  const json = fs.readFileSync(await ordner.path(), 'utf8');
  const d = JSON.parse(json);
  pruef('Sicherungsdatei ohne Videodaten', json.length < 20000 && !json.includes('video/webm'));
  console.log('  Datei:', JSON.stringify(d.nachricht));
  pruef('Datei vermerkt Video und Ablage', d.nachricht.video.aufgenommen.length === 10 && d.nachricht.videoAblage === 'USB-Stick im Ordner Testament');
  pruef('Bereich gilt als begonnen', await p.evaluate(() => PRUEFUNG.nachricht(zustand.daten)[0]));
  await p.click('#btnDrucken');
  await p.click('dialog button:has-text("Drucken")').catch(() => {});
  const druck = await p.textContent('#druck');
  pruef('Ausdruck nennt Video und Ablage', druck.includes('Es gibt eine Videonachricht, aufgenommen am') && druck.includes('Wo liegt eine Kopie der Videonachricht?'));
  await p.evaluate(() => window.dispatchEvent(new Event('afterprint')));
  await p.click('button:has-text("Video löschen")');
  await p.click('dialog button:has-text("Video löschen")');
  await p.waitForSelector('button:has-text("Video aufnehmen")');
  pruef('Video gelöscht', await p.evaluate(async () => !(await speicher.videoLesen()) && zustand.daten.nachricht.video.aufgenommen === ''));
  // Beim Löschen des Ordners verschwindet auch das Video
  const [w2] = await Promise.all([p.waitForEvent('filechooser'), p.click('button:has-text("Vorhandenes Video auswählen")')]);
  pruef('Auswahl ohne Kamerazwang', await p.getAttribute('#videowahl', 'capture') === null);
  await w2.setFiles(video);
  await p.waitForSelector('video.videonachricht');
  await p.click('#navStart button');
  await p.click('#btnMehr').then(() => p.click('#btnLoeschen'));
  pruef('Löschdialog erwähnt das Video', await p.isVisible('dialog >> text=Auch die Videonachricht'));
  await p.click('dialog button:has-text("Endgültig löschen")');
  await p.waitForSelector('#startseite:not([hidden])');
  pruef('Video mit dem Ordner gelöscht', await p.evaluate(async () => !(await speicher.videoLesen())));
} finally {
  console.log('Fehler:', fehler);
  await browser.close();
  server.kill();
}
