// Prüft die Eingabe des Geburtsdatums als Ziffern: Punkte automatisch, Prüfung, Speicherung, Anzeige, Druck.
import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
import path from 'path';
const hier = path.dirname(new URL(import.meta.url).pathname);
const url = 'file://' + path.join(hier, '../dist/klarordner.html');
const pruef = (was, ja) => console.log(`  ${ja ? 'ok ' : 'FEHLT'} ${was}`);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const fehler = [];
const p = await (await browser.newContext({ locale: 'de-DE', viewport: { width: 820, height: 1180 }, hasTouch: true })).newPage();
await p.addInitScript(() => { delete window.showOpenFilePicker; delete window.showSaveFilePicker; window.print = () => {}; });
p.on('pageerror', e => fehler.push(e.message));
p.on('console', m => { if (m.type() === 'error') fehler.push(m.text()); });
await p.goto(url);
await p.click('#btnNeu');
await p.waitForSelector('.kacheln');
await p.click('.kachel:has-text("Persönliche Daten")');
const feld = p.locator('.feld', { has: p.locator('label', { hasText: /^Geburtsdatum$/ }) });
const eingabe = feld.locator('input');
pruef('Textfeld mit Zahlentastatur statt Kalender', await eingabe.getAttribute('type') === 'text' && await eingabe.getAttribute('inputmode') === 'numeric');
await eingabe.click();
await p.keyboard.type('17031952');
pruef('Punkte werden automatisch gesetzt', await eingabe.inputValue() === '17.03.1952');
pruef('Gespeichert als Datum', await p.evaluate(() => zustand.daten.persoenlich.geburtsdatum) === '1952-03-17');
await eingabe.fill('');
await p.keyboard.type('3.7.1948');
pruef('Eingabe mit eigenen Punkten', await p.evaluate(() => zustand.daten.persoenlich.geburtsdatum) === '1948-07-03');
await eingabe.fill('');
await p.keyboard.type('31021950');
await p.keyboard.press('Tab');
pruef('Ungültiges Datum wird angezeigt', await feld.locator('.fehler').isVisible());
pruef('Ungültiges Datum nicht gespeichert', await p.evaluate(() => zustand.daten.persoenlich.geburtsdatum) === '');
await eingabe.fill('');
await p.keyboard.type('28021950');
await p.keyboard.press('Tab');
pruef('Fehlerhinweis verschwindet', !(await feld.locator('.fehler').isVisible()));
// Löschen mit der Rücktaste setzt keine Punkte neu
await eingabe.click();
await p.keyboard.press('End');
for (let i = 0; i < 5; i++) await p.keyboard.press('Backspace');
pruef('Rücktaste funktioniert', await eingabe.inputValue() === '28.02');
await eingabe.fill('');
await eingabe.dispatchEvent('input');
pruef('Leeren löscht das Datum', await p.evaluate(() => zustand.daten.persoenlich.geburtsdatum) === '');
await eingabe.click();
await p.keyboard.type('17031952');
// Wie Safari bei Autofill oder Einfügen: ganzer Wert auf einmal, ohne Ereignisdetails
await eingabe.fill('');
await p.evaluate(() => { const i = document.querySelector('.datumfeld'); i.value = '17031952'; i.dispatchEvent(new Event('input', { bubbles: true })); });
pruef('Acht Ziffern am Stück werden angenommen', await p.evaluate(() => zustand.daten.persoenlich.geburtsdatum) === '1952-03-17' && await eingabe.inputValue() === '17.03.1952');
await p.evaluate(() => { const i = document.querySelector('.datumfeld'); i.value = '5/11/1949'; i.dispatchEvent(new Event('input', { bubbles: true })); i.dispatchEvent(new Event('change', { bubbles: true })); });
pruef('Andere Trennzeichen beim Verlassen übernommen', await p.evaluate(() => zustand.daten.persoenlich.geburtsdatum) === '1949-11-05' && await eingabe.inputValue() === '05.11.1949');
await eingabe.fill('');
await p.keyboard.type('17031952');
// Anzeige nach dem Neuladen und im Schreiben
await p.waitForTimeout(700);
await p.reload();
await p.click('.kachel:has-text("Persönliche Daten")');
pruef('Nach Neustart als TT.MM.JJJJ angezeigt', await eingabe.inputValue() === '17.03.1952');
const satz = await p.evaluate(() => briefInhalt({ art: 'leer', id: 'x' }).absaetze[0]);
pruef('Im Schreiben eingesetzt', satz.includes('geboren am 17.03.1952'));
console.log('Fehler:', fehler);
await browser.close();
